passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "AAAAC3NzaC1lZDI1NTE5AAAAIOwRm8uTw4YmVVVusiLxTc0NRLMXaW9spe3jFTsJLMq9 89:06:fb:09:32:57:7c:cd:11:1e:c6:64:c1:a3:68:ad id_ed25519"
storage:
  files:
    - path: /etc/modules-load.d/bridge-netfilter.conf
      filesystem: root
      mode: 0644
      contents:
        inline: br_netfilter
    - path: /etc/sysctl.d/nf.conf
      filesystem: root
      mode: 0644
      contents:
        inline: |
                  net.bridge.bridge-nf-call-ip6tables = 1
                  net.bridge.bridge-nf-call-iptables = 1
    - filesystem: "root"
      path:       "/etc/hostname"
      mode:       0644
      contents:
        inline: flatcar1
    - filesystem: "root"
      path:       "/etc/hosts"
      mode:       0644
      contents:
        inline: |
          127.0.0.1 localhost
          ::1       localhost
          127.0.0.1 flatcar1
          ::1       flatcar1
